"""
PocketBot Enterprise X

Trading Pipeline models.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TypeAlias

from pocketbot.decision.result import DecisionResult
from pocketbot.indicators.base.result import IndicatorResult
from pocketbot.market.models.market_snapshot import MarketSnapshot
from pocketbot.market.strategy.models import StrategyResult
from pocketbot.risk.models.risk_assessment import (
    RiskAssessment,
)
from pocketbot.score.result import ScoreResult


TradingMetadataValue: TypeAlias = (
    str
    | int
    | float
    | bool
    | None
)


@dataclass(frozen=True, slots=True)
class TradingRequest:
    """
    Request used to execute the trading pipeline.
    """

    asset: str

    timeframe: int

    indicators: list[str] = field(
        default_factory=list,
    )


@dataclass(frozen=True, slots=True)
class TradingResult:
    """
    Complete result generated by the trading pipeline.
    """

    market: MarketSnapshot

    indicators: list[IndicatorResult]

    score: ScoreResult

    strategy: StrategyResult | None

    decision: DecisionResult

    risk: RiskAssessment

    metadata: dict[str, TradingMetadataValue] = field(
        default_factory=dict,
    )