"""
PocketBot Enterprise X

Execution Order.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from pocketbot.domain.enums import SignalType


@dataclass(frozen=True, slots=True)
class ExecutionOrder:
    """
    Immutable order generated by the Execution Engine.
    """

    asset: str

    signal: SignalType

    timeframe: int

    amount: float

    confidence: float

    expiration: int

    metadata: dict[str, Any] = field(default_factory=dict)

    created_at: datetime = field(
        default_factory=lambda: datetime.now(UTC),
    )
