from datetime import datetime, UTC


class IntelligenceMetrics:
    """
    Runtime metrics collector for Enterprise Intelligence layer.

    Stores operational intelligence events
    generated by autonomous analysis components.
    """

    def __init__(self):
        self.events = []

    def record(self, name: str, value: float):
        """
        Register an intelligence metric event.
        """

        self.events.append(
            {
                "name": name,
                "value": value,
                "timestamp": datetime.now(UTC),
            }
        )

    def latest(self, limit: int = 10):
        """
        Return latest intelligence events.
        """

        return self.events[-limit:]

    def count(self):
        """
        Return total number of recorded events.
        """

        return len(self.events)

    def clear(self):
        """
        Clear collected intelligence metrics.
        """

        self.events.clear()
